import { createContext, useContext, useState, type ReactNode, type ButtonHTMLAttributes } from 'react'
import { Check, CheckCircle2, ChevronRight, Copy, Eye, Inbox, LoaderCircle, X, AlertCircle, type LucideIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Device, Log } from './api'
import { formatTime } from './api'

export function Button({children, busy, variant='primary', className='', type='button', disabled, ...props}: ButtonHTMLAttributes<HTMLButtonElement> & {busy?:boolean; variant?:'primary'|'secondary'|'ghost'|'danger'}) {return <button className={`btn btn-${variant} ${className}`} {...props} type={type} disabled={busy || disabled}>{busy && <LoaderCircle size={16} className="spin"/>}{children}</button>}
export function Heading({eyebrow, title, description, children}: {eyebrow?:string;title:string;description:string;children?:ReactNode}) {return <div className="page-heading"><div><div className="eyebrow">{eyebrow || 'WORKSPACE'}</div><h1>{title}</h1><p>{description}</p></div><div className="heading-actions">{children}</div></div>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function CardTitle({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}){return <div className="card-title"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{children}</div>}
export function Empty({icon:Icon=Inbox,title,description,children}:{icon?:LucideIcon;title:string;description:string;children?:ReactNode}){return <div className="empty"><div className="empty-icon"><Icon size={26}/></div><h3>{title}</h3><p>{description}</p>{children}</div>}
export function ErrorBox({error}:{error:string}){return error ? <div className="error-box" role="alert"><AlertCircle size={18}/><span>{error}</span></div>:null}
export function Loading(){return <div className="loading"><LoaderCircle className="spin" size={24}/><span>Memuat workspace…</span></div>}
export function Badge({online,label}:{online?:boolean;label?:string}){return <span className={`badge ${online?'online':'offline'}`}><span className="status-dot"/>{label || (online?'Online':'Offline')}</span>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>}
export function CopyButton({value,label='Salin'}:{value:string;label?:string}){const [copied,setCopied]=useState(false); const notify=useToast();return <Button type="button" variant="secondary" aria-label={label} onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{notify('Gagal menyalin. Salin teks secara manual.','error')}}}>{copied?<Check size={15}/>:<Copy size={15}/>}<span>{copied?'Tersalin':label}</span></Button>}
export function DeviceSelect({devices,value,onChange,multiple=false}:{devices:Device[];value:string;onChange:(v:string)=>void;multiple?:boolean}){return <Field label="Perangkat pengirim"><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Pilih perangkat online</option>{devices.map(d=><option key={d.phone} value={d.phone} disabled={!d.online}>+{d.number} · {d.online?'Online':'Offline'}</option>)}</select>{!devices.some(d=>d.online) && <small>Hubungkan perangkat melalui <Link to="/devices">halaman Perangkat</Link>.</small>}</Field>}
export function ResponseBox({result}:{result:unknown}){return result!==null && result!==undefined ? <div className="response"><div className="eyebrow">RESPONS API</div><pre>{JSON.stringify(result,null,2)}</pre></div>:null}
export function LogTable({rows}:{rows:Log[]}){const [selected,setSelected]=useState<Log|null>(null);return <><div className="table-wrap log-table-desktop"><table><thead><tr><th>Tujuan</th><th>Pesan</th><th>Jenis</th><th>Waktu</th><th>Detail</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="mono">{row.receiver||'—'}</td><td><span className="truncate-message" title={row.message}>{row.message}</span></td><td><span className="tag">{row.type==='OUTGOING'?'Terkirim':row.type}</span></td><td className="muted nowrap">{formatTime(row.timestamp)}</td><td><button type="button" className="log-detail-button" onClick={()=>setSelected(row)}><Eye size={15}/>Detail</button></td></tr>)}</tbody></table></div><div className="log-mobile-list">{rows.map(row=><article className="log-mobile-card" key={row.id}><div className="log-mobile-top"><span className="tag">{row.type==='OUTGOING'?'Terkirim':row.type}</span><time>{formatTime(row.timestamp)}</time></div><strong className="mono">{row.receiver||'Tujuan tidak tercatat'}</strong><p>{row.message||'Tidak ada isi pesan'}</p><button type="button" className="log-detail-button" onClick={()=>setSelected(row)}><Eye size={15}/>Lihat detail pesan</button></article>)}</div>{selected&&<Modal title="Detail pesan" onClose={()=>setSelected(null)}><dl className="log-detail-list"><div><dt>ID log</dt><dd>{selected.id}</dd></div><div><dt>Waktu</dt><dd>{formatTime(selected.timestamp)}</dd></div><div><dt>Pengirim</dt><dd>{selected.sender||'—'}</dd></div><div><dt>Tujuan</dt><dd>{selected.receiver||'—'}</dd></div><div><dt>Jenis / status</dt><dd>{selected.type==='OUTGOING'?'Terkirim':selected.type}</dd></div></dl><div className="log-detail-message"><div><strong>Isi pesan</strong><CopyButton value={selected.message||''} label="Salin pesan"/></div><pre>{selected.message||'Tidak ada isi pesan yang tercatat.'}</pre></div></Modal>}</>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="card-title"><h2>{title}</h2><button className="icon-button" aria-label="Tutup dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>}
export function ArrowLink({to,children}:{to:string;children:ReactNode}){return <Link className="text-link" to={to}>{children}<ChevronRight size={15}/></Link>}
const ToastContext=createContext<(message:string,kind?:'success'|'error')=>void>(()=>{})
export function useToast(){return useContext(ToastContext)}
export function ToastProvider({children}:{children:ReactNode}){const [toast,setToast]=useState<{message:string;kind:string}|null>(null);return <ToastContext.Provider value={(message,kind='success')=>{setToast({message,kind});setTimeout(()=>setToast(null),5000)}}>{children}{toast && <div role="status" className={`toast ${toast.kind}`}>{toast.kind==='success'?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>}<span>{toast.message}</span><button aria-label="Tutup notifikasi" onClick={()=>setToast(null)}><X size={16}/></button></div>}</ToastContext.Provider>}
