import { test, expect } from '@playwright/test'

test('CS nested buttons, typed replies, editor persistence, and responsive layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const username = `csui${Date.now()}`
  await page.goto('/register')
  await page.getByLabel('Username', { exact: false }).fill(username)
  await page.getByLabel('Password', { exact: true }).fill('Testing-password-2026')
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('Testing-password-2026')
  await page.getByRole('button', { name: 'Buat akun Utusan' }).click()
  await expect(page.getByRole('heading', { name: `Halo, ${username}.` })).toBeVisible()
  await page.goto('/customer-service')
  await expect(page.getByRole('heading', { name: 'Bot CS', exact: true })).toBeVisible()
  const bubble = page.locator('.cs-chat-bubble')
  const options = page.locator('.cs-reply-options')
  await expect(bubble).toContainText('Selamat datang')
  await options.getByRole('button', { name: 'Bantuan / FAQ' }).click()
  await expect(bubble).toContainText('Pusat bantuan')
  await options.getByRole('button', { name: 'Jam operasional' }).click()
  await expect(bubble).toContainText('Jam operasional')
  await options.getByRole('button', { name: 'Menu utama' }).click()
  await expect(bubble).toContainText('Selamat datang')
  await page.getByLabel('Balasan uji pelanggan').fill('2')
  await page.getByRole('button', { name: 'Uji balasan', exact: true }).click()
  await expect(bubble).toContainText('Pusat bantuan')
  await page.getByLabel('Nomor admin', { exact: false }).fill('628123456789')
  await page.getByLabel('Aktifkan Bot CS').check()
  await page.locator('.cs-node-tabs').getByRole('button', { name: 'Jam operasional', exact: true }).click()
  await page.getByLabel('Pesan balasan', { exact: false }).fill('Layanan tersedia Senin–Jumat, 09.00–17.00.')
  await expect(bubble).toContainText('09.00–17.00')
  await page.getByRole('button', { name: 'Simpan pengaturan' }).click()
  await expect(page.getByRole('status')).toContainText('Pengaturan Bot CS disimpan')
  await page.reload()
  await expect(page.getByLabel('Aktifkan Bot CS')).toBeChecked()
  await options.getByRole('button', { name: 'Bantuan / FAQ' }).click()
  await options.getByRole('button', { name: 'Jam operasional' }).click()
  await expect(bubble).toContainText('09.00–17.00')
  await page.getByRole('button', { name: 'Kembali ke menu utama' }).click()
  await options.getByRole('button', { name: 'Hubungi admin' }).click()
  await expect(bubble).toContainText('https://wa.me/628123456789')
  await page.getByLabel('Jenis balasan').selectOption('list')
  await expect(bubble).toContainText('Selamat datang')
  for (const width of [375, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.sidebar')).toHaveCSS('transform', 'matrix(1, 0, 0, 1, -270, 0)')
  await page.screenshot({ path: 'test-results/customer-service-mobile.png', fullPage: true })
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark' })
  await page.screenshot({ path: 'test-results/customer-service-dark-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/customer-service-desktop.png', fullPage: true })
  expect(errors).toEqual([])
})
